### ISSUE TITLE
Install fails to load external modules

### ISSUE THREAD

**Issue by trezero** [peoplewareDo/generator-ng2-seed-advanced#5]
Whats the status of this project? It sounds like it would be fantastic, but I cant seem to get it to install. Is there a list of prerequisite files/applications that are needed?

In Mac OSX 10.11.4 I'm seeing this

npm install -g yo 
- This command works

npm install -g generator-ng2-seed-advanced
Produces this fine bit of fun:
├── vinyl (global)
├── vinyl-source-stream (global)
├── yargs (global)
└── zone.js (global)

[12:59:50] Failed to load external module ts-node/register
[12:59:50] Failed to load external module typescript-node/register
[12:59:50] Failed to load external module typescript-register
[12:59:50] Failed to load external module typescript-require
/usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
/usr/local/lib
└── (empty)

npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-ng2-seed-advanced"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /GitHubNoDropBox/Angular/Angular2/npm-debug.log
npm ERR! code 1

**Comment by ivanstan** [comment]
I got something similar on Windows: 

[18:22:38] Failed to load external module ts-node/register
[18:22:38] Failed to load external module typescript-node/register
[18:22:38] Failed to load external module typescript-register
[18:22:38] Failed to load external module typescript-require
C:\Users\ivan\AppData\Roaming\npm\node_modules\generator-ng2-seed-advanced\node_modules\angular2-seed-advanced\gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import \* as gulp from 'gulp';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (C:\Users\ivan\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\ivan\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
C:\Users\ivan\AppData\Roaming\npm
`-- (empty)

npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "generator-ng2-seed-advanced"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ivan\npm-debug.log
npm ERR! code 1

**Comment by victorsosa** [comment]
This seems to be a dependency issue with typescript package; You should do `npm install -g typings` before install this package

**Comment by ivanstan** [comment]
Tried but unfortunately still got error. I was concerned with this permission denied error so I ran both commands as super user...

npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/spawn-sync
> node postinstall
> 
> angular2-seed-advanced@1.0.0 postinstall /usr/local/lib/node_modules/generator-ng2-seed-advanced/node_modules/angular2-seed-advanced
> typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js

/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:54
                throw err;
                ^

Error: EACCES: permission denied, open '/var/root/.config/configstore/typings.json'
You don't have access to this file.

```
at Error (native)
at Object.fs.openSync (fs.js:634:18)
at Object.fs.readFileSync (fs.js:502:33)
at Object.create.all.get (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:35:26)
at Object.Configstore (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:28:44)
at Object.<anonymous> (/usr/local/lib/node_modules/typings/node_modules/typings-core/dist/utils/store.js:5:19)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
```

/usr/local/lib
└── (empty)

npm WARN @ngrx/store@2.2.1 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ngrx/store@2.2.1 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm WARN @ngrx/core@1.2.0 requires a peer of rxjs@^5.0.0-beta.12 but none was installed.
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-ng2-seed-advanced"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! angular2-seed-advanced@1.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed-advanced@1.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed-advanced package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver && node tools/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed-advanced
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed-advanced
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ivan.stanojevic/projects/npm-debug.log
npm ERR! code 1
sh-3.2#

**Comment by victorsosa** [comment]
Ok I updated the angular2-seed-advanced to v1.0.1 dependency, can you try to do a fresh install?

and let me know.

**Comment by EddMontalbano** [comment]
If anyone else is running into this, you must also run `npm install -g typescript-node typescript`

**Comment by victorsosa** [comment]
I did another update to angular2-seed-advanced to v1.0.2; the template project is pointing to a deprecated package:

`npm WARN deprecated es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.`

I double check and that was already fixed in the last release.
`"es-module-loader": "^1.0.0"`

please update or install again.
